version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: weekly
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
      groups:
          react:
              patterns:
                  - "@types/react"
                  - "@types/react-dom"
                  - "react"
                  - "react-dom"
          storybook:
              patterns:
                  - "@storybook/*"
                  - "storybook"
          vite:
              patterns:
                  - "vite"
                  - "vite-plugin-dts"
                  - "vitest"
          eslint:
              patterns:
                  - "eslint"
                  - "eslint-*"
                  - "@typescript-eslint/eslint-plugin"
                  - "@typescript-eslint/parser"
                  - "@trivago/prettier-plugin-sort-imports"
